# Generated by Django 2.0.7 on 2018-07-15 04:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_manager', '0005_auto_20180713_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018, validators=[django.core.validators.MaxValueValidator(2035), django.core.validators.MinValueValidator(2015)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'month', 'year')},
        ),
    ]
