# Generated by Django 2.0.7 on 2018-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0008_auto_20180715_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=72),
        ),
    ]
